name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.x

      - name: Bump version
        run: deno run --allow-read=deno.json --allow-write=deno.json --allow-run=git jsr:@kellnerd/bump ${{ github.event.inputs.level }} --commit "chore: Release version " --tag v

      - name: Push changes
        run: |
          git push origin main
          git push origin --tags

      - name: Get the latest tag
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Publish package
        run: deno publish

      - name: Create release
        run: gh release create ${{ steps.tag.outputs.tag }} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
