name: Test

on:
  push:
    paths:
      - 'deno.*'
      - '**/*.ts'
      - '**/*.html'

jobs:
  test:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.x

      # Disabling AppArmor is necessary for tests that require unprivileged user namespaces,
      # which are restricted by default. This step is safe because the CI environment is ephemeral
      # and isolated. Ensure this step is only executed in secure environments.
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Run tests
        run: deno test --allow-all

      - name: Commit lockfile changes
        if: startsWith(github.ref_name, 'renovate/')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes to deno.lock
          if git diff --quiet deno.lock; then
            echo "No lockfile changes detected"
          else
            echo "Lockfile changes detected, committing..."
            git add deno.lock
            git commit -m "chore: Update deno.lock"
            git push
          fi
